[package]
name = "qalam-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "تلوين الأكواد - Syntax highlighting for Tarqeem"

[dependencies]
tree-sitter.workspace = true
thiserror.workspace = true
